# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md for all rules.
default: true
MD013: false
MD024:
  siblings_only: true
MD025: false
MD033: false
MD041: false
MD046: false
MD049: false
MD045: false
MD029: false
MD036: false
